### PR TITLE
Model explanation 11

### PR DESCRIPTION
**Pull request by dschoenig**
Fixes issue #11 for the French and English versions. For details see discussion of the issue.

### CODE REVIEW

**Comment by pedrohbraga** [comment]
Hi, Daniel (@dschoenig)! Thank you so much for this! I am going to wait for Travis CI's pass on the workshop, which should take a few hours. Once it is done, we will approve, merge the pull request and get back to you about the changes you have added!

**Comment by LaurieMaynard** [comment]
I found some typos and here and there and some slide missing translation. I can fix it on this branch before you merge it.

**Comment by LaurieMaynard** [comment]
My changes has been implemented into this branch and it should be good to be reviewed and merge with the main branch

**Comment by dschoenig** [comment]
Great, thanks for having another look at this, Laurie!

**Comment by dschoenig** [comment]
Going through the slides there was only one potential inaccuracy I noticed: The condition for the residuals is that they should be independent and identically distributed -- I think the equivalent French term would be `residus idépendants et identiquement distribués` (see https://fr.wikipedia.org/wiki/Variables_ind%C3%A9pendantes_et_identiquement_distribu%C3%A9es), as  `uniformément distribués` (current version line 586) would imply that they come from a uniform distribution when they come in fact all from the same normal distribution N(0, σ²). 

However my knowledge on the correct statistical terms in French is definitely spotty, so it would be great if someone of you could shed some light on this!

**Comment by LaurieMaynard** [comment]
Sorry, I know you wrote identiquement, but I changed it because I never heard that word and thougth it didn't exist (I just check and apparently it does). When I wrote uniformément distribué cause to me it means that they are spread evenly across the plot. I never heard identiquement in that context, but we can put it back. If not, maybe another word would be better, such as "également" not to confuse anyone.

**Pull request merged**
